services:
  db-oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: db-oracle
    environment:
      - ORACLE_PASSWORD=${ORACLE_ADMIN_PASSWORD}
      - APP_USER=${ORACLE_USER}
      - APP_USER_PASSWORD=${ORACLE_PASSWORD}
    ports:
      - "${ORACLE_PORT}:1521"
    
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD","healthcheck.sh"]
      interval: 10s
      retries: 20
      timeout: 5s
      start_period: 60s
  
volumes:
  oracle-data: